name: jekyll test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build with Jekyll
      run: |
        sudo apt-get update  
        sudo apt-get install --assume-yes ruby-full build-essential zlib1g-dev liblzma-dev git < /dev/null  
        gem install -v "1.16.4" bundler --no-ri --no-rdoc 
        bundle update github-pages 
        bundle install --without development test 
        bundle exec jekyll build --config _config.yml,_config-root.yml
