name: jekyll test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build with Jekyll
      run: |
        # sudo apt-get update  
        sudo apt-get install --assume-yes ruby-full build-essential zlib1g-dev liblzma-dev git < /dev/null  
        mkdir ~/.ruby
        export GEM_HOME=~/.ruby/
        export PATH="$PATH:~/.ruby/bin"
        gem install -v "1.16.4" bundler --no-ri --no-rdoc 
        bundle update github-pages 
        bundle install --without development test 
        bundle exec jekyll build 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install mill
      run: |
        mkdir bin
        sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/lihaoyi/Ammonite/releases/download/1.8.1/2.13-1.8.1) > bin/amm && chmod +x bin/amm' 
    - name: Test for broken links
      run: bin/amm checklinks.sc


