name: update postdoc alumni

on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Update links from spreadsheet
      run: ./amm postdoc-alumni.sc
    - name: Update in repository
      uses: test-room-7/action-update-file@v1
      with:
          file-path: |
              _data/postdoc-alumni.yaml
              _data/inspire-alumni.yaml
          commit-msg: Updated postdoc alumni
          github-token: ${{ secrets.GITHUB_TOKEN }}
